name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python_version: '3.10'
      - name: Build APK
        run: |
          pip install buildozer
          buildozer init
          # هاد السطر هو اللي يخرج الـ APK
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: bin/*.apk
