name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Buildozer
        run: pip install buildozer
      - name: Build APK
        run: |
          buildozer init
          sed -i 's/package.name = myapp/package.name = ze8csystem/' buildozer.spec
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          # أمر البناء المباشر
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: bin/*.apk
